### ISSUE TITLE
Error when parsing Silva taxonomies

### ISSUE THREAD

**Issue by antgonza** [biocore/empress#129]
This is more an FYI as this was previously reported in QIIME2: https://forum.qiime2.org/t/qiime-taxa-filter-table-error/3947/10

If you try to use Silva based taxonomies you get this error:
```bash
There was an issue with viewing the artifact merged_seqs-taxonomy-silva.qza as QIIME 2 Metadata:

  CategoricalMetadataColumn does not support values with leading or trailing whitespace characters. Column 'Taxon' has the following value: 'D_0__Bacteria;D_1__Gemmatimonadetes;D_2__Gemmatimonadetes;D_3__Gemmatimonadales;D_4__Gemmatimonadaceae;D_5__Gemmatimonas;D_6__uncultured bacterium '
```

**Comment by fedarko** [comment]
@antgonza I'm working on testing that this error is resolved right now -- do you happen to still have the data that caused this lying around?

**Comment by fedarko** [comment]
Ok, updates on this: I can replicate the error @antgonza reported by, in QIIME 2 _2019.7_, running `qiime metadata tabulate` on the taxonomy file he was using (thanks for sharing it with me!). In QIIME 2 _2019.10_, the error is fixed, and the taxonomy file can be viewed as metadata without the error. I confirmed also that generating an Empress visualization from @antgonza's files works without an error in QIIME 2 2019.10.\*

This is because [the issue causing this problem](https://github.com/qiime2/q2-types/issues/179) was fixed in the 2019.10 version of QIIME 2, so I've just updated the README accordingly to request that users use at least that version. Just to be super extra careful, I've also added [tests](https://github.com/fedarko/empress/blob/8a9b4fb42a9e2aae5f1f7a6938e035192499c790/tests/python/test_taxonomy_utils.py#L248-L300) that verify that leading/trailing whitespace (including testing the exact `D_5__Gemmatimonas` annotation above) are handled properly.

So I think we can close this issue when the feature metadata branch (to which the above changes have been made) is merged in.

\* (I had to generate the visualization on barnacle, since my computer killed the Empress python code... when I tried to view the resulting QZV on chrome, my browser wouldn't load it after ~5 minutes so I just gave up. However, the visualization was at least generated successfully. This is more motivation for improving the tool's performance as discussed in #74, #151, etc.)

**Comment by antgonza** [comment]
Thank you @fedarko! 

BTW the shared files are from a meta-analysis from 3 host types (rats, mice, human) and _only_ 5 qiita studies ... highlighting the importance of fixing/improving those other issues!

**Comment by antgonza** [comment]
Thinking about this, @fedarko, @ElDeveloper should those performance issues be part of the alpha release?

**Comment by ElDeveloper** [comment]
@esayyari is working on a PR to make loading times faster. We should be able to hear more updates from him soon.
