### ISSUE TITLE
Tree won't update line widths or colors

### ISSUE THREAD

**Issue by samanthagoldman** [biocore/empress#157]
Hi all,

I used Empress through qiime2 to create a visualization of an insertion tree I built. I can visualize the tree through qiime2view, but when I try to change the branch width or color by metadata column, nothing happens. I read on another issue that this could take a while, but I don't think time is the problem I have. Not sure if this is an error on my end or not, but if anyone has any ideas that would be much appreciated.

Thank you!
Sam

**Comment by ElDeveloper** [comment]
@samanthagoldman thanks for reporting this issue 🌲 . Did you make sure to click the "Update" button on the bottom left side of the right-hand-side panel?

![Screen Shot 2020-04-16 at 9 26 33 AM](https://user-images.githubusercontent.com/375307/79481696-b417d600-7fc4-11ea-9d14-ff6e5af3602e.png)

If you don't see any changes, would you mind sharing your visualization?

**Comment by samanthagoldman** [comment]
Yes, I hit the button. And I've tried with several different trees, so I don't think its an issue with one specific .qza

**Comment by ElDeveloper** [comment]
Would you be able to share the visualization with us?

**Comment by samanthagoldman** [comment]
Thanks for your help!  Here's a link to the file on box:
https://cornell.box.com/s/zd2rg1e0n8jmvp185axyvn0hfkz682eh

**Comment by fedarko** [comment]
Thanks for sharing the file! This looks like a problem with Empress' code -- whenever the "Update" button is clicked in this visualization, a `TypeError: this._nameToKeys[names[i]] is undefined` error message shows up in the console.

![uhohspaghettios](https://user-images.githubusercontent.com/4177727/79786923-032e7580-82fb-11ea-9ff1-543e87f1215b.png)

I think I've run into this sort of error in the past due to "matching" problems between files; from digging into the surrounding code, my guess is that the problem is due to there being features in the feature table QZA you provided Empress that aren't also in the tree QZA you provided Empress (leading to the error shown here).

I think the latest version of Empress (as of 5 minutes ago, thanks to @ElDeveloper :) should avoid this problem; could you try reinstalling and then regenerating the visualization with that to see if this fixes things? I'm guessing you will need to use the `--p-filter-missing-features` parameter as well.

**Comment by ElDeveloper** [comment]
@samanthagoldman did you have a chance to try @fedarko's suggestion? If that didn't work feel free to re-open this issue.
