### ISSUE TITLE
Colors not updating (alert the user when there's no unique features)

### ISSUE THREAD

**Issue by pavlo888** [biocore/empress#161]
Hi, 

First of all, this new tool looks awesome! But I am trying to visualise the tree based on different metadata colors and I only get coloured lines when the metadata variable has only one value, but no colouring when the metadata variable has more than one value. 

![Screenshot 2020-05-24 at 00 36 43](https://user-images.githubusercontent.com/45701394/82741865-25327200-9d57-11ea-81e8-735c0916c8ad.png)
![Screenshot 2020-05-24 at 00 36 34](https://user-images.githubusercontent.com/45701394/82741866-26639f00-9d57-11ea-9355-41907fc5a1a0.png)

Would you please let me know how to fix this problem? 

Cheers, 
Pablo

**Comment by kwcantrell** [comment]
@pavlo888 would you be able to share your data? 

Currently, sample based metadata coloring works by assigning colors to "unique branches." For example, say you have observations (or tips)  a,b,c,d and samples s1,s2,s3, s4 with a metadata field Replicate where s1 has Replicate value 1, s2 has value 2, and s3/s4 have value 3. If 'a' seen in both s1 and s2 then 'a' is not considered unique because it is associated with values 1 and 2. However, say 'c' is seen in both s3 and s4 then it is considered unique because it is only associated with samples with value 3. 

So, one possible cause could be that you do not have any "unique" observations for the Replicate field. Since Matrix only has one value, all observations would be considered unique which is why they are colored.

**Comment by pavlo888** [comment]
Hi @kwcantrell 

Thank you for your fast response. I could share my data, should I send it to your email? 

Based on beta diversity, my samples are very similar but still have show a differential significant p-value. 

Regarding the replicate field, I did not expect any unique features but on the rest of the metadata fields I do expect differences, albeit small. 

Cheers, 
Pablo

**Comment by kwcantrell** [comment]
No problem, you can send it to kcantrel@ucsd.edu.

**Comment by pavlo888** [comment]
Hi there,

I am sending you the data I used for empress. I will kindly ask you to
exercise discretion with this data since the data has not yet been
published.

Cheers,
Pablo
