### ISSUE TITLE
dude where's my tree? (add recenter camera)

### ISSUE THREAD

**Issue by antgonza** [biocore/empress#172]
Playing around with the tutorial I realized that if a user zooms "too much", you can't bring back your tree, like here:
![where](https://user-images.githubusercontent.com/2014559/84569669-ab821880-ad45-11ea-89c1-74a8e6d5ca9e.gif)

In case it helps this is the error in the console:
<img width="1870" alt="Screen Shot 2020-06-13 at 7 11 02 AM" src="https://user-images.githubusercontent.com/2014559/84569673-b3da5380-ad45-11ea-8ac0-32fa34994829.png">

Anyway, perhaps it will be worth adding a "recenter" button?

**Comment by fedarko** [comment]
This is a really good point, agreed that having a "recenter" button would be useful. This functionality (if it doesn't already exist in the JS code somewhere?) would also be very useful to automatically apply when changing layouts, since the tree's bounding boxes differs for each layout. (Also, I like the issue name ;)

I'm not sure the tree missing here is related to the console warnings (those show up during normal usage of Empress, which may be something to fix in and of itself) -- I think it's more likely that the tree is still drawn somewhere but it's just super difficult to "find" due to the new camera position after zooming being so far off. (In the GIF, I can see the tree sort of go flying towards the bottom of the camera as the camera is zoomed in above where the tree is positioned.)

**Comment by ElDeveloper** [comment]
That's a good suggestion - and even better title. I think a recenter camera button would be great to add.
