### ISSUE TITLE
Use more or less line segments for certain arcs in the circular layout

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#372]
Based on something like angle distance? We've talked about this before (it came up on Tuesday morning's meeting), and it'd be good to keep track of it.

Basically, all arcs in the circular layout connecting the highest- and lowest- angle child nodes of an internal node are approximated by 15 line segments right now.

![image](https://user-images.githubusercontent.com/4177727/92152184-20aa3a80-edd7-11ea-8863-d91eda216236.png)

This looks good for most use cases, but for particularly large trees this can look jagged -- so approximating this with more segments (I think @kwcantrell mentioned 60 on Tuesday?) would be nice.

Similarly, for many small arcs (covering a short angle distance), using 15 segments is overkill -- and these could be approximated with ~1-5 segments instead without looking noticeably different. This would probably save us some time for large trees.

I think setting up a small function that takes in a lowest / highest angle value and computes a "number of segments needed" might be a good way to go about this -- doesn't have to be exact or anything, and could be refined as needed.

**Comment by kwcantrell** [comment]
Thanks @fedarko  for bringing this up. I am currently working on a branch to solve this issue [https://github.com/kwcantrell/empress/tree/smooth-arcs](https://github.com/kwcantrell/empress/tree/smooth-arcs).

It follows a dynamic approach that adjust the # of segments based on the total angle of the arc (i.e. the closer the arc is the a full circle the more segments are drawn). This approach not only makes the larger arcs much smooth but we also get a pretty nice speed boast since the vast majority of arcs can be approximated with 1 or 2 segments.

**Comment by fedarko** [comment]
Closed by #377!
