### ISSUE TITLE
Error installing Empress

### ISSUE THREAD

**Issue by OliverAshton1** [biocore/empress#552]
Hello

I am trying to install empress into qiime2 2021.11 on Windows 10 WSL (Ubuntu 20.04.3 LTS (GNU/Linux 5.10.60.1-microsoft-standard-WSL2 x86_64)), versions attached. I have attached a copy of the full error below. The rest of Qiime2 works fine for me.

Any help is appreciated. 
Oliver

[Empress Error.txt](https://github.com/biocore/empress/files/7660282/Empress.Error.txt)

[Versions.txt](https://github.com/biocore/empress/files/7664020/Versions.txt)

**Comment by fedarko** [comment]
Hi @OliverAshton1,

Thanks for the detailed report. I just checked, and was able to install Empress using pip into a new QIIME 2 2021.11 environment (with the same software versions as you've listed in `Versions.txt`) on a Linux computer. This, together with the exact error message you got, implies that things are going wrong when installing the `iow` library into your system.

The origin of the installation error seems to occur when trying to build one of `iow`'s dependencies (line 81 of your error message file):

```
  ar -csru libbitarr.a bit_array.o
  make: ar: No such file or directory
  make: *** [Makefile:25: libbitarr.a] Error 127
```

From what I can tell, the reason you're running into this problem is that the [`ar`](https://en.wikipedia.org/wiki/Ar_(Unix)) command (which creates / extracts certain types of archives) is not installed on your system (and it looks like it is installed on my Linux system already, so this would explain why I don't encounter this problem when installing Empress).

It seems like `ar` is part of the [`binutils`](https://en.wikipedia.org/wiki/GNU_Binutils) package, so I think that installing `binutils` should then allow you to install Empress. Long story short, **could you please try installing `binutils`, and then try re-installing Empress**? I'm not very familiar with WSL, but [from some googling](https://github.com/microsoft/WSL/issues/2486) I think something like

```
sudo apt-get install binutils
```

should do the trick for installing `binutils` in WSL.

Let us know if this works out!

**Comment by OliverAshton1** [comment]
Hi @fedarko 

As you recommended I used: 
```
conda activate qiime2-2021.11
sudo apt-get install binutils
pip install empress
qiime dev refresh-cache
qiime empress --help
```

binutils installed 6 new packages, then Empress installed first time, on both my PCs that showed the error.
Many thanks for your quick reply!

Oliver

**Comment by fedarko** [comment]
Fantastic, thanks @OliverAshton1! Glad that worked.

I just created a new issue (#553): we'll add this information to EMPress' documentation to help other people who run into this problem in the future, since I imagine that other WSL users may also encounter this.
